#!/bin/bash

# Arch Linux
# Установка базы linux

reflector -l 3 --sort rate --save /etc/pacman.d/mirrorlist

echo 'Установка основных пакетов'
pacstrap /mnt base linux linux-firmware

echo 'Настройка системы, запись таблицы файловых систем'
genfstab -pU /mnt >> /mnt/etc/fstab

arch-chroot /mnt