#!/bin/bash

# Arch Linux
# Установка загрузчика 

# echo 'Создадим загрузочный RAM диск'
# mkinitcpio -p linux

source ./VARIABLE

echo 'Устанавливаем загрузчик'
mount /dev/nvme0n1p1 /mnt/boot
pacman -Syy
pacman -S grub efibootmgr --noconfirm
grub-install /dev/nvme0n1

echo 'Обновляем grub.cfg'
grub-mkconfig -o /boot/grub/grub.cfg