#!/bin/bash

# Arch Linux
# Задание основных перменных для установки

source ./VARIABLE

echo "Заданные параметры установки"
echo "====================================="
echo.
echo "Диск установки: $disk"
echo "Имя компьютера: $hostname"
echo "Добавить пользователя: $username"
echo.
echo "====================================="

read -p "Введите имя диска для установки (sda, sdb или nvme0n1 ): " disk
read -p "Введите имя компьютера: " hostname
read -p "Введите имя пользователя: " username

rm VARIABLE
echo "disk=$disk" > VARIABLE
echo "hostname=$hostname" > VARIABLE
echo "username=$username" > VARIABLE


source ./VARIABLE

echo "Заданные новые параметры установки"
echo "====================================="
echo.
echo "Диск установки: $disk"
echo "Имя компьютера: $hostname"
echo "Добавить пользователя: $username"
echo.
echo "====================================="