#!/bin/bash

# Arch Linux
# Задание основных перменных для установки

clear

source ./VARIABLE

echo "Заданные параметры установки"
echo "====================================="
echo ""
echo "Диск установки: $disk"
echo "Имя компьютера: $hostname"
echo "Добавить пользователя: $username"
echo "Добавить пользователя: $soft"
echo ""
echo "====================================="

echo "Все переменные вводяться без пробелов (можно заменить на тире - или подчеркиваени _ )"

read -p "Введите имя диска для установки (sda, sdb или nvme0n1 ): " disk
read -p "Введите имя компьютера: " hostname
read -p "Введите имя пользователя: " username
read "Установка дополнительного софта (пример: nano git vim и т.п.): " soft

rm VARIABLE
echo "disk="$disk"" > VARIABLE
echo "hostname="$hostname"" >> VARIABLE
echo "username="$username"" >> VARIABLE
echo "soft="$soft"" >> VARIABLE


source ./VARIABLE

echo "Внесены новые переменные для установки"
echo "====================================="
echo ""
echo "Диск установки: $disk"
echo "Имя компьютера: $hostname"
echo "Добавить пользователя: $username"
echo "Добавить пользователя: $soft"
echo ""
echo "====================================="