#!/bin/bash

# Arch Linux
# Задание основных перменных для установки

clear

if [ -f "./VARIABLE" ]
  then
  source ./VARIABLE

  echo "Заданные параметры установки"
  echo "====================================="
  echo ""
  echo "Диск установки: $disk"
  echo "Имя компьютера: $hostname"
  echo "Пользователи: $username"
  echo "Дополнительный софт для установки: $soft"
  echo ""
  echo "====================================="

  else
  echo "Задать переменые для установки"
fi

echo "Данные вводяться без пробелов (пробел можно заменить на тире - или подчеркиваени _ )"

read -p "Введите имя диска для установки (sda, sdb или nvme0n1 ): " disk
read -p "Введите имя компьютера: " hostname
read -p "Введите имя пользователя: " username
read -p "Установка дополнительного софта (пример: nano git vim и т.п.): " soft

if [ -f "./VARIABLE" ]
  then
  echo "Предыдущие настройки удалены"
  rm -rf ./VARIABLE
  else
  echo "Создан новый файл установок"
fi

echo "disk=\"$disk\"" > VARIABLE
echo "hostname=\"$hostname\"" >> VARIABLE
echo "username=\"$username\"" >> VARIABLE
echo "soft=\"$soft\"" >> VARIABLE

source ./VARIABLE

echo "Внесены новые переменные для установки"
echo "====================================="
echo ""
echo "Диск установки: $disk"
echo "Имя компьютера: $hostname"
echo "Добавить пользователя: $username"
echo "Добавить пользователя: $soft"
echo ""
echo "======================================"