#!/bin/bash

# Arch Linux
# Установка дополнительный пакетов и другого софта

echo 'Раскомментируем репозиторий multilib Для работы 32-битных приложений в 64-битной системе.'
echo '[multilib]' >> /etc/pacman.conf
echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
pacman -Syy

echo 'Установка дополнительных пакетов'
pacman -S nano vim git dhcpcd netctl